.TH "C:/Users/anna.kleshchenko/Documents/GitHub/task-tracker/src Directory Reference" 3 "Sat Sep 24 2022" "Лаба2_Клещенко_МКС223" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anna.kleshchenko/Documents/GitHub/task-tracker/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcomponents\fP"
.br
.ti -1c
.RI "directory \fBData\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBApp\&.js\fP"
.br
.ti -1c
.RI "file \fBApp\&.test\&.js\fP"
.br
.ti -1c
.RI "file \fBindex\&.js\fP"
.br
.ti -1c
.RI "file \fBreportWebVitals\&.js\fP"
.br
.ti -1c
.RI "file \fBsetupTests\&.js\fP"
.br
.ti -1c
.RI "file \fBThemeContext\&.js\fP"
.br
.in -1c
