.TH "C:/Users/anna.kleshchenko/Documents/GitHub/task-tracker/src/components/Project/ProjectPage.js" 3 "Sat Sep 24 2022" "Лаба2_Клещенко_МКС223" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anna.kleshchenko/Documents/GitHub/task-tracker/src/components/Project/ProjectPage.js
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Лаба2_Клещенко_МКС223 from the source code\&.
